clouds:
  KIS:
    region_name: "{{ OS_REGION_NAME }}"
    identity_api_version: "3"
    identity_interface: "internal"
    auth:
      username: "{{ OS_USERNAME }}"
      password: "{{ OS_PASSWORD }}"
      project_name: "{{ OS_PROJECT_NAME }}"
      project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
      user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
      auth_url: "{{ OS_AUTH_URL }}"
    cacert: |
      ---- BEGIN CERTIFICATE ---
      ...
    verify: false
