#!/bin/bash


echo "OS-env_$(date +%Y%m%d%H%M%S).txt"

env | grep -E 'OS_REGION_NAME|OS_AUTH_VERSION|OS_CACERT|OS_AUTH_URL|OS_PROJECT_DOMAIN_NAME|OS_AUTH_PROTOCOL|OS_USERNAME|OS_AUTH_TYPE|OS_USER_DOMAIN_NAME|OS_PROJECT_NAME|OS_PASSWORD|OS_IDENTITY_API_VERSION' | sed -E 's/(.*)=(.*)/\1=\2/' > OS-env.txt
